[tool.ruff]
line-length = 125
indent-width = 4
target-version = "py312"
lint.select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake8-type-checking
    "TC",
]